from flask import Flask, render_template, request

app = Flask(__name__, static_folder='static', static_url_path='/static')

TRANSLATIONS = {
    'pt': {
        'meta_titulo': 'Lupinus Life — O teu novo superalimento',
        'meta_descripcion': 'Lupinus Life: snack de tremoço e milho chulpi torrado. 24g de proteína por dose. Vegano, sem glúten e 100% natural.',
        'img_alt': 'Lupinus Life — Snack de tremoço e milho chulpi torrado',
        'subtitulo': 'Snack natural · Vegano · Sem glúten',
        'marca_linea1': 'LUPINUS',
        'marca_linea2': 'LIFE',
        'marca_completa': 'LUPINUS LIFE',
        'slogan': 'El teu novo superalimento chegou',
        'descripcion_nueva': 'A combinação destes tenros e suaves lupinos andinos com o crocante milho chulpi tostado oferece uma mistura de sabores única, com todos os elementos essenciais para recarregar a tua energia e alimentar-te de forma saudável.',
        'experimente': 'Experimente já!',
        'features_titulo': 'Porquê escolher Lupinus Life?',
        'descubre_diferencia': 'Tremoço Tradicional ou Lupino Andino? Descobre a diferença:',
        'titulo_tremoco': '🍺 Tremoço Tradicional',
        'titulo_lupino': '⛰️ Lupino Andino',
        'comp_header': 'Característica',
        'c1_tit': 'Perfil Proteico', 'c1_t': '~15g (Básico, energia a curto prazo)', 'c1_l': '✅ 24g (Premium, saciedade prolongada)',
        'c2_tit': 'O Segredo da Casca (Consumo)', 'c2_t': 'Descartada. É espessa, dura e atua como uma esponja para a água salgada.', 'c2_l': '✅ Consumida a 100%. A pele é extrafina, macia e funde-se com o grão a cada trinca.',
        'c3_tit': 'Fibras e Digestão', 'c3_t': 'Perdes metade da fibra ao deitar fora a casca no prato.', 'c3_l': '✅ Aproveitamento total. Fibra integral e prebiótica intacta, pois comes o grão inteiro.',
        'c4_tit': 'Conveniência e Limpeza', 'c4_t': 'Suja as mãos com líquidos e exige um prato para cuspir as cascas.', 'c4_l': '✅ 100% On-the-Go. Sem lixo, sem líquidos a escorrer, abre e come em movimento.',
        'c5_tit': 'Qualidade e Calibre', 'c5_t': 'Produto de massa, tamanhos mistos e irregulares', 'c5_l': '✅ Seleção Premium (8mm), origem agroecológica',
        'c6_tit': 'Estado e Textura', 'c6_t': 'Escorregadio e mole', 'c6_l': '✅ Firme, denso e com um crunch perfeito (com o milho)',
        'c7_tit': 'Sódio / Sal', 'c7_t': 'Muito elevado (provoca sede e retenção de líquidos)', 'c7_l': '✅ Equilibrado e natural (focado na saúde cardiovascular)',
        'c8_tit': 'Gorduras Boas', 'c8_t': 'Níveis residuais', 'c8_l': '✅ Rico em Ómegas 3, 6 e 9 (energia cerebral)',
        'c9_tit': 'Preço e Volume', 'c9_t': '✅ Hiper-económico, o clássico "snack de cêntimos"', 'c9_l': 'Investimento nutricional de valor premium',
        'c10_tit': 'Nostalgia e Tradição', 'c10_t': '✅ O clássico indiscutível das esplanadas e festas de verão', 'c10_l': 'Um conceito novo focado na performance desportiva/diária',
        'c11_tit': 'Frescura Húmida', 'c11_t': '✅ Proporciona frescura imediata por estar mergulhado em água', 'c11_l': 'É um snack seco (ideal para acompanhar a tua bebida favorita)',
        'feature_1_titulo': 'Fonte natural de proteína',
        'feature_1_desc': '24g de proteína vegetal de alta qualidade em cada porção.',
        'feature_2_titulo': 'Sem conservantes nem corantes',
        'feature_2_desc': 'Apenas ingredientes naturais, sem aditivos artificiais.',
        'feature_3_titulo': 'Pronto a consumir',
        'feature_3_desc': 'Abre, desfruta. Nutrição instantânea onde quiseres.',
        'feature_4_titulo': 'Vegano e sem glúten',
        'feature_4_desc': 'Adequado para todos os estilos de vida e dietas.',
        'highlight_1': 'Proteína Vegetal',
        'highlight_2': 'Energia Natural',
        'highlight_3': 'Alto em Fibra',
        'highlight_4': '100% Natural',
        'highlight_frase': 'Crocante, saboroso e cheio de benefícios.',
        'usability_titulo': 'Desenhado para o teu estilo de vida',
        'usability_subtitulo': 'Lupinus Life adapta-se a cada momento do teu dia.',
        'usability_1_titulo': 'Ideal para desportistas',
        'usability_1_desc': 'Recuperação e desempenho com proteína vegetal de qualidade.',
        'usability_2_titulo': 'Perfeito para o dia a dia',
        'usability_2_desc': 'Um snack nutritivo para qualquer momento do dia.',
        'usability_3_titulo': 'Prático para levar onde quiseres',
        'usability_3_desc': 'Formato compacto, pronto para a mochila ou mala.',
        'usability_4_titulo': 'Energia que dura mais',
        'usability_4_desc': 'Fibra e proteína para uma saciedade prolongada.',
        'nutrition_titulo': 'Informação Nutricional',
        'nutrition_subtitulo': 'Valores por porção de 150g',
        'nutrition_header': 'Valor Nutricional',
        'nutrition_porcion': 'Porção: 150g',
        'nutrition_energia': 'Energia',
        'nutrition_proteinas': 'Proteínas',
        'nutrition_grasas': 'Gorduras Totais',
        'nutrition_fibra': 'Fibra',
        'nutrition_disclaimer': '* Valores orientativos. Consulta a embalagem para informação detalhada.',
        'footer_tagline': 'El teu novo superalimento · O teu novo superalimento',
        'footer_copyright': '© 2026 Lupinus Life. Todos os direitos reservados.',
    },
    'es': {
        'meta_titulo': 'Lupinus Life — Tu nuevo superalimento',
        'meta_descripcion': 'Lupinus Life: snack de chocho/tremoço y maíz chulpi tostado. 24g de proteína por dosis. Vegano, sin gluten y 100% natural.',
        'img_alt': 'Lupinus Life — Snack de chocho y maíz chulpi tostado',
        'subtitulo': 'Snack natural · Vegano · Sin gluten',
        'marca_linea1': 'LUPINUS',
        'marca_linea2': 'LIFE',
        'marca_completa': 'LUPINUS LIFE',
        'slogan': 'Tu nuevo superalimento ha llegado',
        'descripcion_nueva': 'La combinación de estos tiernos y suaves chochos andinos con el crocante maíz chulpi tostado ofrece una mezcla de sabores única, con todos los elementos esenciales para recargar tu energía y alimentarte de forma saludable.',
        'experimente': '¡Pruébalo ya!',
        'features_titulo': '¿Por qué elegir Lupinus Life?',
        'descubre_diferencia': '¿Altramuz Tradicional o Chocho Andino? Descubre la diferencia:',
        'titulo_tremoco': '🍺 Altramuz Tradicional',
        'titulo_lupino': '⛰️ Chocho Andino',
        'comp_header': 'Característica',
        'c1_tit': 'Perfil Proteico', 'c1_t': '~15g (Básico, energía a corto plazo)', 'c1_l': '✅ 24g (Premium, saciedad prolongada)',
        'c2_tit': 'El Secreto de la Cáscara (Consumo)', 'c2_t': 'Descartada. Es gruesa, dura y actúa como esponja para el agua salada.', 'c2_l': '✅ Consumida al 100%. La piel es extrafina, suave y se funde con el grano en cada bocado.',
        'c3_tit': 'Fibras y Digestión', 'c3_t': 'Pierdes la mitad de la fibra al tirar la cáscara al plato.', 'c3_l': '✅ Aprovechamiento total. Fibra integral y prebiótica intacta, ya que comes el grano entero.',
        'c4_tit': 'Conveniencia y Limpieza', 'c4_t': 'Ensucia las manos con líquidos y exige un plato para escupir las cáscaras.', 'c4_l': '✅ 100% On-the-Go. Sin basura, sin líquidos que escurran, abre y come en movimiento.',
        'c5_tit': 'Calidad y Calibre', 'c5_t': 'Producto de masas, tamaños mixtos e irregulares.', 'c5_l': '✅ Selección Premium (8mm), origen agroecológico.',
        'c6_tit': 'Estado y Textura', 'c6_t': 'Resbaladizo y blando.', 'c6_l': '✅ Firme, denso y con un crunch perfecto (con el maíz).',
        'c7_tit': 'Sodio / Sal', 'c7_t': 'Muy elevado (provoca sed y retención de líquidos).', 'c7_l': '✅ Equilibrado y natural (enfocado en la salud cardiovascular).',
        'c8_tit': 'Grasas Buenas', 'c8_t': 'Niveles residuales.', 'c8_l': '✅ Rico en Omegas 3, 6 y 9 (energía cerebral).',
        'c9_tit': 'Precio y Volumen', 'c9_t': '✅ Híper-económico, el clásico "snack de céntimos".', 'c9_l': 'Inversión nutricional de valor premium.',
        'c10_tit': 'Nostalgia y Tradición', 'c10_t': '✅ El clásico indiscutible de las terrazas y fiestas de verano.', 'c10_l': 'Un concepto nuevo enfocado en el rendimiento deportivo/diario.',
        'c11_tit': 'Frescura Húmeda', 'c11_t': '✅ Proporciona frescura inmediata al estar sumergido en agua.', 'c11_l': 'Es un snack seco (ideal para acompañar tu bebida favorita).',
        'feature_1_titulo': 'Fuente natural de proteína',
        'feature_1_desc': '24g de proteína vegetal de alta calidad en cada porción.',
        'feature_2_titulo': 'Sin conservantes ni colorantes',
        'feature_2_desc': 'Solo ingredientes naturales, sin aditivos artificiales.',
        'feature_3_titulo': 'Listo para consumir',
        'feature_3_desc': 'Abre, disfruta. Nutrición instantánea donde quieras.',
        'feature_4_titulo': 'Vegano y sin gluten',
        'feature_4_desc': 'Apto para todos los estilos de vida y dietas.',
        'highlight_1': 'Proteína Vegetal',
        'highlight_2': 'Energía Natural',
        'highlight_3': 'Alto en Fibra',
        'highlight_4': '100% Natural',
        'highlight_frase': 'Crocante, sabroso y lleno de beneficios.',
        'usability_titulo': 'Diseñado para tu estilo de vida',
        'usability_subtitulo': 'Lupinus Life se adapta a cada momento de tu día.',
        'usability_1_titulo': 'Ideal para deportistas',
        'usability_1_desc': 'Recuperación y rendimiento con proteína vegetal de calidad.',
        'usability_2_titulo': 'Perfecto para el día a día',
        'usability_2_desc': 'Un snack nutritivo para cualquier momento del día.',
        'usability_3_titulo': 'Práctico para llevar donde quieras',
        'usability_3_desc': 'Formato compacto, listo para la mochila o el bolso.',
        'usability_4_titulo': 'Energía que dura más',
        'usability_4_desc': 'Fibra y proteína para una saciedad prolongada.',
        'nutrition_titulo': 'Información Nutricional',
        'nutrition_subtitulo': 'Valores por porción de 150g',
        'nutrition_header': 'Valor Nutricional',
        'nutrition_porcion': 'Porción: 150g',
        'nutrition_energia': 'Energía',
        'nutrition_proteinas': 'Proteínas',
        'nutrition_grasas': 'Grasas Totales',
        'nutrition_fibra': 'Fibra',
        'nutrition_disclaimer': '* Valores orientativos. Consulta el envase para información detallada.',
        'footer_tagline': 'Tu nuevo superalimento ha llegado',
        'footer_copyright': '© 2026 Lupinus Life. Todos los derechos reservados.',
    },
    'en': {
        'meta_titulo': 'Lupinus Life — Your new superfood',
        'meta_descripcion': 'Lupinus Life: lupin and toasted chulpi corn snack. 24g of protein per serving. Vegan, gluten-free and 100% natural.',
        'img_alt': 'Lupinus Life — Lupin and toasted chulpi corn snack',
        'subtitulo': 'Natural snack · Vegan · Gluten-free',
        'marca_linea1': 'LUPINUS',
        'marca_linea2': 'LIFE',
        'marca_completa': 'LUPINUS LIFE',
        'slogan': 'Your new superfood has arrived',
        'descripcion_nueva': 'The combination of these tender and soft Andean lupins with the crunchy toasted chulpi corn offers a unique flavor mix, with all the essential elements to recharge your energy and feed you healthily.',
        'experimente': 'Try it now!',
        'features_titulo': 'Why choose Lupinus Life?',
        'descubre_diferencia': 'Traditional Lupin or Andean Lupin? Discover the difference:',
        'titulo_tremoco': '🍺 Traditional Lupin',
        'titulo_lupino': '⛰️ Andean Lupin',
        'comp_header': 'Feature',
        'c1_tit': 'Protein Profile', 'c1_t': '~15g (Basic, short-term energy)', 'c1_l': '✅ 24g (Premium, prolonged satiety)',
        'c2_tit': 'The Secret of the Skin (Consumption)', 'c2_t': 'Discarded. It is thick, hard and acts like a sponge for salty water.', 'c2_l': '✅ 100% consumed. The skin is extra-thin, soft and melts with the bean in every bite.',
        'c3_tit': 'Fibre and Digestion', 'c3_t': 'You lose half the fibre by throwing the skin on the plate.', 'c3_l': '✅ Total utilization. Intact whole and prebiotic fibre, as you eat the whole bean.',
        'c4_tit': 'Convenience and Cleanliness', 'c4_t': 'Gets hands dirty with liquids and requires a plate to spit the skins.', 'c4_l': '✅ 100% On-the-Go. No trash, no dripping liquids, open and eat on the move.',
        'c5_tit': 'Quality and Caliber', 'c5_t': 'Mass product, mixed and irregular sizes.', 'c5_l': '✅ Premium Selection (8mm), agroecological origin.',
        'c6_tit': 'State and Texture', 'c6_t': 'Slippery and soft.', 'c6_l': '✅ Firm, dense and with a perfect crunch (with the corn).',
        'c7_tit': 'Sodium / Salt', 'c7_t': 'Very high (causes thirst and fluid retention).', 'c7_l': '✅ Balanced and natural (focused on cardiovascular health).',
        'c8_tit': 'Good Fats', 'c8_t': 'Residual levels.', 'c8_l': '✅ Rich in Omegas 3, 6 and 9 (brain energy).',
        'c9_tit': 'Price and Volume', 'c9_t': '✅ Hyper-economical, the classic "penny snack".', 'c9_l': 'Premium value nutritional investment.',
        'c10_tit': 'Nostalgia and Tradition', 'c10_t': '✅ The undisputed classic of terraces and summer parties.', 'c10_l': 'A new concept focused on sports/daily performance.',
        'c11_tit': 'Moist Freshness', 'c11_t': '✅ Provides immediate freshness by being soaked in water.', 'c11_l': 'It is a dry snack (ideal to accompany your favorite drink).',
        'feature_1_titulo': 'Natural source of protein',
        'feature_1_desc': '24g of high-quality plant protein in every serving.',
        'feature_2_titulo': 'No preservatives or colourings',
        'feature_2_desc': 'Only natural ingredients, no artificial additives.',
        'feature_3_titulo': 'Ready to eat',
        'feature_3_desc': 'Open, enjoy. Instant nutrition wherever you go.',
        'feature_4_titulo': 'Vegan and gluten-free',
        'feature_4_desc': 'Suitable for all lifestyles and diets.',
        'highlight_1': 'Plant Protein',
        'highlight_2': 'Natural Energy',
        'highlight_3': 'High in Fibre',
        'highlight_4': '100% Natural',
        'highlight_frase': 'Crunchy, tasty and full of benefits.',
        'usability_titulo': 'Designed for your lifestyle',
        'usability_subtitulo': 'Lupinus Life fits every moment of your day.',
        'usability_1_titulo': 'Ideal for athletes',
        'usability_1_desc': 'Recovery and performance with quality plant protein.',
        'usability_2_titulo': 'Perfect for everyday life',
        'usability_2_desc': 'A nutritious snack for any time of day.',
        'usability_3_titulo': 'Easy to take anywhere',
        'usability_3_desc': 'Compact format, ready for your backpack or bag.',
        'usability_4_titulo': 'Energy that lasts longer',
        'usability_4_desc': 'Fibre and protein for lasting satiety.',
        'nutrition_titulo': 'Nutritional Information',
        'nutrition_subtitulo': 'Values per 150g serving',
        'nutrition_header': 'Nutritional Value',
        'nutrition_porcion': 'Serving: 150g',
        'nutrition_energia': 'Energy',
        'nutrition_proteinas': 'Protein',
        'nutrition_grasas': 'Total Fat',
        'nutrition_fibra': 'Fibre',
        'nutrition_disclaimer': '* Approximate values. Check the packaging for detailed information.',
        'footer_tagline': 'Your new superfood has arrived',
        'footer_copyright': '© 2026 Lupinus Life. All rights reserved.',
    },
}


@app.route('/')
def home():
    lang = request.args.get('lang', 'pt')
    if lang not in TRANSLATIONS:
        lang = 'pt'
    return render_template('index.html', lang=lang, t=TRANSLATIONS[lang])


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)